CREATE TABLE IF NOT EXISTS public.%s (
  id SERIAL PRIMARY KEY,
  author_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  value TEXT NOT NULL,
  setted_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);