CREATE TABLE IF NOT EXISTS public.%s (
  id SERIAL PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  email TEXT,
  role_id INT NOT NULL,
  hash TEXT,
  token TEXT,
  created_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);